baseURL = "https://shashankgsharma.github.io/"
languageCode = "en-us"
title = "Shashank Sharma"
theme = "PaperMod"

[params]
  author = "Shashank Sharma"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/shashankgsharma"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/shashankgsharma"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:shashank.0901sharma@gmail.com"


[params.profileMode]
  enabled = true
  title = "Shashank Sharma"
  subtitle = "AI/ML Researcher | NLP | Summarization | Incoming @ TCS Research"

  [[params.profileMode.buttons]]
    name = "Resume"
    url = "/files/resume.pdf"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

  [[params.profileMode.buttons]]
    name = "Publications"
    url = "/publications/"

  [[params.profileMode.buttons]]
    name = "Blog"
    url = "/posts/"

