baseURL = "https://shashankgsharma.github.io/"
languageCode = "en-us"
title = "Shashank Sharma"
theme = "PaperMod"

[params]
  author = "Shashank Sharma"
  mainSections = ["posts"]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/shashankgsharma"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/shashankgsharma"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:shashank.0901sharma@gmail.com"


[params.profileMode]
  enabled = true
  imageUrl = "/profile.jpg"
  imageTitle = "Shashank Sharma"
  imageWidth = 160
  imageHeight = 160
  title = "Shashank Sharma"
  subtitle = "AI Research | RnD @ TCS Research | Neuromorphic Computing"

  [[params.profileMode.buttons]]
    name = "CV"
    url = "/files/resume.pdf"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

#  [[params.profileMode.buttons]]
#    name = "Publications"
#    url = "/publications/"

  [[params.profileMode.buttons]]
    name = "Blog"
    url = "/posts/"


[params.homeInfoParams]
Title = "Research Notes & Projects"
Content = "I write about paper implementations, NLP research, and career learnings."

[params.assets]
favicon = "/favicon/favicon.ico"
favicon16x16 = "/favicon/favicon-16x16.png"
favicon32x32 = "/favicon/favicon-32x32.png"
apple_touch_icon = "/favicon/apple-touch-icon.png"
android_chrome192x192 = "/favicon/android-chrome-192x192.png"
android_chrome512x512 = "/favicon/android-chrome-512x512.png"
